CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Categoria" (
        cat_id integer GENERATED BY DEFAULT AS IDENTITY,
        cat_nombre text,
        CONSTRAINT "PK_Categoria" PRIMARY KEY (cat_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "MetodoPago" (
        pag_id integer GENERATED BY DEFAULT AS IDENTITY,
        pag_metodo text,
        pag_fecha date NOT NULL,
        CONSTRAINT "PK_MetodoPago" PRIMARY KEY (pag_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Servicio" (
        ser_id integer GENERATED BY DEFAULT AS IDENTITY,
        ser_nombre text NOT NULL,
        ser_descripcion text NOT NULL,
        ser_imagen text NOT NULL,
        CONSTRAINT "PK_Servicio" PRIMARY KEY (ser_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Usuario" (
        usu_id text NOT NULL,
        usu_nombre text,
        usu_apellido text,
        "usu_nombrePerfil" text,
        "usu_numIdentificacion" text,
        usu_correo text,
        CONSTRAINT "PK_Usuario" PRIMARY KEY (usu_id),
        CONSTRAINT "FK_Usuario_AspNetUsers_usu_id" FOREIGN KEY (usu_id) REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Autoparte" (
        aut_id integer GENERATED BY DEFAULT AS IDENTITY,
        aut_nombre text,
        aut_descripcion text,
        aut_precio numeric NOT NULL,
        aut_especificacion text,
        aut_cantidad integer NOT NULL,
        aut_imagen text NOT NULL,
        "CategoriaId" integer NOT NULL,
        CONSTRAINT "PK_Autoparte" PRIMARY KEY (aut_id),
        CONSTRAINT "FK_Autoparte_Categoria_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categoria" (cat_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Carrito" (
        car_id integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" text NOT NULL,
        CONSTRAINT "PK_Carrito" PRIMARY KEY (car_id),
        CONSTRAINT "FK_Carrito_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" (usu_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Encuesta" (
        encuesta_id integer GENERATED BY DEFAULT AS IDENTITY,
        agrado_sistema text NOT NULL,
        facilidad_pago text NOT NULL,
        nps_score integer NOT NULL,
        fecha_envio timestamp with time zone NOT NULL,
        comentarios text,
        usu_id text NOT NULL,
        CONSTRAINT "PK_Encuesta" PRIMARY KEY (encuesta_id),
        CONSTRAINT "FK_Encuesta_Usuario_usu_id" FOREIGN KEY (usu_id) REFERENCES "Usuario" (usu_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Reclamacion" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" text NOT NULL,
        "TipoReclamacion" text NOT NULL,
        "TipoEntidad" text NOT NULL,
        "EntidadId" integer NOT NULL,
        "Descripcion" character varying(1000) NOT NULL,
        "Estado" text NOT NULL,
        "Respuesta" text,
        "FechaReclamacion" timestamp with time zone NOT NULL,
        "FechaRespuesta" timestamp with time zone,
        "NumeroReferencia" text NOT NULL,
        "Monto" numeric NOT NULL,
        CONSTRAINT "PK_Reclamacion" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Reclamacion_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" (usu_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Reserva" (
        res_id integer GENERATED BY DEFAULT AS IDENTITY,
        res_placa text NOT NULL,
        res_telefono text NOT NULL,
        res_fecha timestamp with time zone NOT NULL,
        res_hora interval NOT NULL,
        res_detalle text,
        "UsuarioId" text NOT NULL,
        ser_id integer NOT NULL,
        "Estado" text NOT NULL,
        CONSTRAINT "PK_Reserva" PRIMARY KEY (res_id),
        CONSTRAINT "FK_Reserva_Servicio_ser_id" FOREIGN KEY (ser_id) REFERENCES "Servicio" (ser_id) ON DELETE CASCADE,
        CONSTRAINT "FK_Reserva_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" (usu_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Venta" (
        ven_id integer GENERATED BY DEFAULT AS IDENTITY,
        ven_fecha date NOT NULL,
        "MetodoPagoId" integer NOT NULL,
        "UsuarioId" text,
        "Total" numeric NOT NULL,
        "StripeSessionId" text,
        "Estado" text NOT NULL,
        "CodigoDescuento" text,
        CONSTRAINT "PK_Venta" PRIMARY KEY (ven_id),
        CONSTRAINT "FK_Venta_MetodoPago_MetodoPagoId" FOREIGN KEY ("MetodoPagoId") REFERENCES "MetodoPago" (pag_id) ON DELETE CASCADE,
        CONSTRAINT "FK_Venta_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" (usu_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "CodigoDescuento" (
        cod_id integer GENERATED BY DEFAULT AS IDENTITY,
        cod_codigo text NOT NULL,
        cod_porcentaje numeric NOT NULL,
        cod_fecha_creacion date NOT NULL,
        cod_fecha_expiracion date NOT NULL,
        cod_utilizado boolean NOT NULL,
        cod_descripcion text NOT NULL,
        "UsuarioId" text,
        "AutoparteId" integer,
        CONSTRAINT "PK_CodigoDescuento" PRIMARY KEY (cod_id),
        CONSTRAINT "FK_CodigoDescuento_Autoparte_AutoparteId" FOREIGN KEY ("AutoparteId") REFERENCES "Autoparte" (aut_id) ON DELETE CASCADE,
        CONSTRAINT "FK_CodigoDescuento_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" (usu_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Entradas" (
        ent_id integer GENERATED BY DEFAULT AS IDENTITY,
        ent_cantidad integer NOT NULL,
        ent_proveedor text,
        ent_fechaent date NOT NULL,
        "AutoparteId" integer NOT NULL,
        CONSTRAINT "PK_Entradas" PRIMARY KEY (ent_id),
        CONSTRAINT "FK_Entradas_Autoparte_AutoparteId" FOREIGN KEY ("AutoparteId") REFERENCES "Autoparte" (aut_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Favoritos" (
        fav_id integer GENERATED BY DEFAULT AS IDENTITY,
        "AutoparteId" integer NOT NULL,
        "UsuarioId" text NOT NULL,
        CONSTRAINT "PK_Favoritos" PRIMARY KEY (fav_id),
        CONSTRAINT "FK_Favoritos_Autoparte_AutoparteId" FOREIGN KEY ("AutoparteId") REFERENCES "Autoparte" (aut_id) ON DELETE CASCADE,
        CONSTRAINT "FK_Favoritos_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" (usu_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Oferta" (
        ofe_id integer GENERATED BY DEFAULT AS IDENTITY,
        ofe_porcentaje numeric NOT NULL,
        ofe_fecha_inicio date NOT NULL,
        ofe_fecha_fin date NOT NULL,
        ofe_descripcion text NOT NULL,
        ofe_activa boolean NOT NULL,
        "AutoparteId" integer NOT NULL,
        CONSTRAINT "PK_Oferta" PRIMARY KEY (ofe_id),
        CONSTRAINT "FK_Oferta_Autoparte_AutoparteId" FOREIGN KEY ("AutoparteId") REFERENCES "Autoparte" (aut_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Resenias" (
        res_id integer GENERATED BY DEFAULT AS IDENTITY,
        res_puntuacion integer NOT NULL,
        res_gusto text NOT NULL,
        res_comentario text NOT NULL,
        res_fecha timestamp with time zone NOT NULL,
        "UsuarioId" text NOT NULL,
        ser_id integer,
        aut_id integer,
        CONSTRAINT "PK_Resenias" PRIMARY KEY (res_id),
        CONSTRAINT "FK_Resenias_Autoparte_aut_id" FOREIGN KEY (aut_id) REFERENCES "Autoparte" (aut_id),
        CONSTRAINT "FK_Resenias_Servicio_ser_id" FOREIGN KEY (ser_id) REFERENCES "Servicio" (ser_id),
        CONSTRAINT "FK_Resenias_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" (usu_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "CarritoAutoparte" (
        "carAut_id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CarritoId" integer NOT NULL,
        "AutoparteId" integer NOT NULL,
        car_cantidad integer NOT NULL,
        car_subtotal numeric NOT NULL,
        CONSTRAINT "PK_CarritoAutoparte" PRIMARY KEY ("carAut_id"),
        CONSTRAINT "FK_CarritoAutoparte_Autoparte_AutoparteId" FOREIGN KEY ("AutoparteId") REFERENCES "Autoparte" (aut_id) ON DELETE CASCADE,
        CONSTRAINT "FK_CarritoAutoparte_Carrito_CarritoId" FOREIGN KEY ("CarritoId") REFERENCES "Carrito" (car_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "OrdenTrabajo" (
        "OrdenTrabajoId" integer GENERATED BY DEFAULT AS IDENTITY,
        "ReservaId" integer NOT NULL,
        "PersonalId" text,
        "AutoparteId" integer,
        "Descripcion" text,
        CONSTRAINT "PK_OrdenTrabajo" PRIMARY KEY ("OrdenTrabajoId"),
        CONSTRAINT "FK_OrdenTrabajo_Autoparte_AutoparteId" FOREIGN KEY ("AutoparteId") REFERENCES "Autoparte" (aut_id),
        CONSTRAINT "FK_OrdenTrabajo_Reserva_ReservaId" FOREIGN KEY ("ReservaId") REFERENCES "Reserva" (res_id) ON DELETE CASCADE,
        CONSTRAINT "FK_OrdenTrabajo_Usuario_PersonalId" FOREIGN KEY ("PersonalId") REFERENCES "Usuario" (usu_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Comprobante" (
        com_id integer GENERATED BY DEFAULT AS IDENTITY,
        tipo_comprobante text NOT NULL,
        "VentaId" integer NOT NULL,
        com_imagen text,
        com_evidencia text,
        CONSTRAINT "PK_Comprobante" PRIMARY KEY (com_id),
        CONSTRAINT "FK_Comprobante_Venta_VentaId" FOREIGN KEY ("VentaId") REFERENCES "Venta" (ven_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "DetalleVentas" (
        det_id integer GENERATED BY DEFAULT AS IDENTITY,
        det_cantidad integer NOT NULL,
        "VentaId" integer NOT NULL,
        "AutoParteId" integer NOT NULL,
        CONSTRAINT "PK_DetalleVentas" PRIMARY KEY (det_id),
        CONSTRAINT "FK_DetalleVentas_Autoparte_AutoParteId" FOREIGN KEY ("AutoParteId") REFERENCES "Autoparte" (aut_id) ON DELETE CASCADE,
        CONSTRAINT "FK_DetalleVentas_Venta_VentaId" FOREIGN KEY ("VentaId") REFERENCES "Venta" (ven_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Boleta" (
        bol_id integer GENERATED BY DEFAULT AS IDENTITY,
        "ComprobanteId" integer NOT NULL,
        num_identificacion text NOT NULL,
        CONSTRAINT "PK_Boleta" PRIMARY KEY (bol_id),
        CONSTRAINT "FK_Boleta_Comprobante_ComprobanteId" FOREIGN KEY ("ComprobanteId") REFERENCES "Comprobante" (com_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Factura" (
        fac_id integer GENERATED BY DEFAULT AS IDENTITY,
        fac_razonsocial text,
        fac_ruc text,
        fac_direccion text,
        "ComprobanteId" integer NOT NULL,
        CONSTRAINT "PK_Factura" PRIMARY KEY (fac_id),
        CONSTRAINT "FK_Factura_Comprobante_ComprobanteId" FOREIGN KEY ("ComprobanteId") REFERENCES "Comprobante" (com_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE TABLE "Salida" (
        sal_id integer GENERATED BY DEFAULT AS IDENTITY,
        sal_fechasalida date NOT NULL,
        sal_cantidad integer NOT NULL,
        "ComprobanteId" integer,
        "AutoparteId" integer NOT NULL,
        CONSTRAINT "PK_Salida" PRIMARY KEY (sal_id),
        CONSTRAINT "FK_Salida_Autoparte_AutoparteId" FOREIGN KEY ("AutoparteId") REFERENCES "Autoparte" (aut_id) ON DELETE CASCADE,
        CONSTRAINT "FK_Salida_Comprobante_ComprobanteId" FOREIGN KEY ("ComprobanteId") REFERENCES "Comprobante" (com_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Autoparte_CategoriaId" ON "Autoparte" ("CategoriaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Boleta_ComprobanteId" ON "Boleta" ("ComprobanteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Carrito_UsuarioId" ON "Carrito" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_CarritoAutoparte_AutoparteId" ON "CarritoAutoparte" ("AutoparteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_CarritoAutoparte_CarritoId" ON "CarritoAutoparte" ("CarritoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_CodigoDescuento_AutoparteId" ON "CodigoDescuento" ("AutoparteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_CodigoDescuento_UsuarioId" ON "CodigoDescuento" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Comprobante_VentaId" ON "Comprobante" ("VentaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_DetalleVentas_AutoParteId" ON "DetalleVentas" ("AutoParteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_DetalleVentas_VentaId" ON "DetalleVentas" ("VentaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Encuesta_usu_id" ON "Encuesta" (usu_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Entradas_AutoparteId" ON "Entradas" ("AutoparteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Factura_ComprobanteId" ON "Factura" ("ComprobanteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Favoritos_AutoparteId" ON "Favoritos" ("AutoparteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Favoritos_UsuarioId" ON "Favoritos" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Oferta_AutoparteId" ON "Oferta" ("AutoparteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_OrdenTrabajo_AutoparteId" ON "OrdenTrabajo" ("AutoparteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_OrdenTrabajo_PersonalId" ON "OrdenTrabajo" ("PersonalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_OrdenTrabajo_ReservaId" ON "OrdenTrabajo" ("ReservaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Reclamacion_UsuarioId" ON "Reclamacion" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Resenias_aut_id" ON "Resenias" (aut_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Resenias_ser_id" ON "Resenias" (ser_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Resenias_UsuarioId" ON "Resenias" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Reserva_ser_id" ON "Reserva" (ser_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Reserva_UsuarioId" ON "Reserva" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Salida_AutoparteId" ON "Salida" ("AutoparteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Salida_ComprobanteId" ON "Salida" ("ComprobanteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Venta_MetodoPagoId" ON "Venta" ("MetodoPagoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    CREATE INDEX "IX_Venta_UsuarioId" ON "Venta" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260314190244_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260314190244_InitialCreate', '10.0.0');
    END IF;
END $EF$;
COMMIT;

