// <auto-generated />
using System;
using Marimon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Marimon.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Favoritos", b =>
                {
                    b.Property<int>("fav_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("fav_id"));

                    b.Property<int>("AutoparteId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("fav_id");

                    b.HasIndex("AutoparteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("Marimon.Models.Autoparte", b =>
                {
                    b.Property<int>("aut_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("aut_id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("aut_cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("aut_descripcion")
                        .HasColumnType("text");

                    b.Property<string>("aut_especificacion")
                        .HasColumnType("text");

                    b.Property<string>("aut_imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("aut_nombre")
                        .HasColumnType("text");

                    b.Property<decimal>("aut_precio")
                        .HasColumnType("numeric");

                    b.HasKey("aut_id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Autoparte");
                });

            modelBuilder.Entity("Marimon.Models.Boleta", b =>
                {
                    b.Property<int>("bol_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("bol_id"));

                    b.Property<int>("ComprobanteId")
                        .HasColumnType("integer");

                    b.Property<string>("num_identificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("bol_id");

                    b.HasIndex("ComprobanteId");

                    b.ToTable("Boleta");
                });

            modelBuilder.Entity("Marimon.Models.Carrito", b =>
                {
                    b.Property<int>("car_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("car_id"));

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("car_id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Carrito");
                });

            modelBuilder.Entity("Marimon.Models.CarritoAutoparte", b =>
                {
                    b.Property<int>("carAut_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("carAut_id"));

                    b.Property<int>("AutoparteId")
                        .HasColumnType("integer");

                    b.Property<int>("CarritoId")
                        .HasColumnType("integer");

                    b.Property<int>("car_cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("car_subtotal")
                        .HasColumnType("numeric");

                    b.HasKey("carAut_id");

                    b.HasIndex("AutoparteId");

                    b.HasIndex("CarritoId");

                    b.ToTable("CarritoAutoparte");
                });

            modelBuilder.Entity("Marimon.Models.Categoria", b =>
                {
                    b.Property<int>("cat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cat_id"));

                    b.Property<string>("cat_nombre")
                        .HasColumnType("text");

                    b.HasKey("cat_id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Marimon.Models.CodigoDescuento", b =>
                {
                    b.Property<int>("cod_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cod_id"));

                    b.Property<int?>("AutoparteId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text");

                    b.Property<string>("cod_codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cod_descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("cod_fecha_creacion")
                        .HasColumnType("date");

                    b.Property<DateTime>("cod_fecha_expiracion")
                        .HasColumnType("date");

                    b.Property<decimal>("cod_porcentaje")
                        .HasColumnType("numeric");

                    b.Property<bool>("cod_utilizado")
                        .HasColumnType("boolean");

                    b.HasKey("cod_id");

                    b.HasIndex("AutoparteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CodigoDescuento");
                });

            modelBuilder.Entity("Marimon.Models.Comprobante", b =>
                {
                    b.Property<int>("com_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("com_id"));

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.Property<string>("com_evidencia")
                        .HasColumnType("text");

                    b.Property<string>("com_imagen")
                        .HasColumnType("text");

                    b.Property<string>("tipo_comprobante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("com_id");

                    b.HasIndex("VentaId");

                    b.ToTable("Comprobante");
                });

            modelBuilder.Entity("Marimon.Models.DetalleVentas", b =>
                {
                    b.Property<int>("det_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("det_id"));

                    b.Property<int>("AutoParteId")
                        .HasColumnType("integer");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.Property<int>("det_cantidad")
                        .HasColumnType("integer");

                    b.HasKey("det_id");

                    b.HasIndex("AutoParteId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("Marimon.Models.Encuesta", b =>
                {
                    b.Property<int>("encuesta_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("encuesta_id"));

                    b.Property<string>("agrado_sistema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("comentarios")
                        .HasColumnType("text");

                    b.Property<string>("facilidad_pago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha_envio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("nps_score")
                        .HasColumnType("integer");

                    b.Property<string>("usu_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("encuesta_id");

                    b.HasIndex("usu_id");

                    b.ToTable("Encuesta");
                });

            modelBuilder.Entity("Marimon.Models.Entradas", b =>
                {
                    b.Property<int>("ent_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ent_id"));

                    b.Property<int>("AutoparteId")
                        .HasColumnType("integer");

                    b.Property<int>("ent_cantidad")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ent_fechaent")
                        .HasColumnType("date");

                    b.Property<string>("ent_proveedor")
                        .HasColumnType("text");

                    b.HasKey("ent_id");

                    b.HasIndex("AutoparteId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Marimon.Models.Factura", b =>
                {
                    b.Property<int>("fac_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("fac_id"));

                    b.Property<int>("ComprobanteId")
                        .HasColumnType("integer");

                    b.Property<string>("fac_direccion")
                        .HasColumnType("text");

                    b.Property<string>("fac_razonsocial")
                        .HasColumnType("text");

                    b.Property<string>("fac_ruc")
                        .HasColumnType("text");

                    b.HasKey("fac_id");

                    b.HasIndex("ComprobanteId");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("Marimon.Models.MetodoPago", b =>
                {
                    b.Property<int>("pag_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("pag_id"));

                    b.Property<DateOnly>("pag_fecha")
                        .HasColumnType("date");

                    b.Property<string>("pag_metodo")
                        .HasColumnType("text");

                    b.HasKey("pag_id");

                    b.ToTable("MetodoPago");
                });

            modelBuilder.Entity("Marimon.Models.Oferta", b =>
                {
                    b.Property<int>("ofe_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ofe_id"));

                    b.Property<int>("AutoparteId")
                        .HasColumnType("integer");

                    b.Property<bool>("ofe_activa")
                        .HasColumnType("boolean");

                    b.Property<string>("ofe_descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ofe_fecha_fin")
                        .HasColumnType("date");

                    b.Property<DateTime>("ofe_fecha_inicio")
                        .HasColumnType("date");

                    b.Property<decimal>("ofe_porcentaje")
                        .HasColumnType("numeric");

                    b.HasKey("ofe_id");

                    b.HasIndex("AutoparteId");

                    b.ToTable("Oferta");
                });

            modelBuilder.Entity("Marimon.Models.OrdenTrabajo", b =>
                {
                    b.Property<int>("OrdenTrabajoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrdenTrabajoId"));

                    b.Property<int?>("AutoparteId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("PersonalId")
                        .HasColumnType("text");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer");

                    b.HasKey("OrdenTrabajoId");

                    b.HasIndex("AutoparteId");

                    b.HasIndex("PersonalId");

                    b.HasIndex("ReservaId");

                    b.ToTable("OrdenTrabajo");
                });

            modelBuilder.Entity("Marimon.Models.Reclamacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaReclamacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("NumeroReferencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Respuesta")
                        .HasColumnType("text");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoReclamacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reclamacion");
                });

            modelBuilder.Entity("Marimon.Models.Resenia", b =>
                {
                    b.Property<int>("res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("res_id"));

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("aut_id")
                        .HasColumnType("integer");

                    b.Property<string>("res_comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("res_fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("res_gusto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("res_puntuacion")
                        .HasColumnType("integer");

                    b.Property<int?>("ser_id")
                        .HasColumnType("integer");

                    b.HasKey("res_id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("aut_id");

                    b.HasIndex("ser_id");

                    b.ToTable("Resenias");
                });

            modelBuilder.Entity("Marimon.Models.Reserva", b =>
                {
                    b.Property<int>("res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("res_id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("res_detalle")
                        .HasColumnType("text");

                    b.Property<DateTime>("res_fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("res_hora")
                        .HasColumnType("interval");

                    b.Property<string>("res_placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("res_telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ser_id")
                        .HasColumnType("integer");

                    b.HasKey("res_id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ser_id");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Marimon.Models.Salida", b =>
                {
                    b.Property<int>("sal_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("sal_id"));

                    b.Property<int>("AutoparteId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComprobanteId")
                        .HasColumnType("integer");

                    b.Property<int>("sal_cantidad")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("sal_fechasalida")
                        .HasColumnType("date");

                    b.HasKey("sal_id");

                    b.HasIndex("AutoparteId");

                    b.HasIndex("ComprobanteId");

                    b.ToTable("Salida");
                });

            modelBuilder.Entity("Marimon.Models.Servicio", b =>
                {
                    b.Property<int>("ser_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ser_id"));

                    b.Property<string>("ser_descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ser_imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ser_nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ser_id");

                    b.ToTable("Servicio");
                });

            modelBuilder.Entity("Marimon.Models.Usuario", b =>
                {
                    b.Property<string>("usu_id")
                        .HasColumnType("text");

                    b.Property<string>("usu_apellido")
                        .HasColumnType("text");

                    b.Property<string>("usu_correo")
                        .HasColumnType("text");

                    b.Property<string>("usu_nombre")
                        .HasColumnType("text");

                    b.Property<string>("usu_nombrePerfil")
                        .HasColumnType("text");

                    b.Property<string>("usu_numIdentificacion")
                        .HasColumnType("text");

                    b.HasKey("usu_id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Marimon.Models.Venta", b =>
                {
                    b.Property<int>("ven_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ven_id"));

                    b.Property<string>("CodigoDescuento")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("integer");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ven_fecha")
                        .HasColumnType("date");

                    b.HasKey("ven_id");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Favoritos", b =>
                {
                    b.HasOne("Marimon.Models.Autoparte", "Autoparte")
                        .WithMany()
                        .HasForeignKey("AutoparteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marimon.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autoparte");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Marimon.Models.Autoparte", b =>
                {
                    b.HasOne("Marimon.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Marimon.Models.Boleta", b =>
                {
                    b.HasOne("Marimon.Models.Comprobante", "Comprobante")
                        .WithMany("Boletas")
                        .HasForeignKey("ComprobanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprobante");
                });

            modelBuilder.Entity("Marimon.Models.Carrito", b =>
                {
                    b.HasOne("Marimon.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Marimon.Models.CarritoAutoparte", b =>
                {
                    b.HasOne("Marimon.Models.Autoparte", "Autoparte")
                        .WithMany()
                        .HasForeignKey("AutoparteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marimon.Models.Carrito", "Carrito")
                        .WithMany("CarritoAutopartes")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autoparte");

                    b.Navigation("Carrito");
                });

            modelBuilder.Entity("Marimon.Models.CodigoDescuento", b =>
                {
                    b.HasOne("Marimon.Models.Autoparte", "Autoparte")
                        .WithMany("CodigosDescuento")
                        .HasForeignKey("AutoparteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Marimon.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Autoparte");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Marimon.Models.Comprobante", b =>
                {
                    b.HasOne("Marimon.Models.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Marimon.Models.DetalleVentas", b =>
                {
                    b.HasOne("Marimon.Models.Autoparte", "Autoparte")
                        .WithMany()
                        .HasForeignKey("AutoParteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marimon.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autoparte");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Marimon.Models.Encuesta", b =>
                {
                    b.HasOne("Marimon.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("usu_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Marimon.Models.Entradas", b =>
                {
                    b.HasOne("Marimon.Models.Autoparte", "Autoparte")
                        .WithMany()
                        .HasForeignKey("AutoparteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autoparte");
                });

            modelBuilder.Entity("Marimon.Models.Factura", b =>
                {
                    b.HasOne("Marimon.Models.Comprobante", "Comprobante")
                        .WithMany("Facturas")
                        .HasForeignKey("ComprobanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprobante");
                });

            modelBuilder.Entity("Marimon.Models.Oferta", b =>
                {
                    b.HasOne("Marimon.Models.Autoparte", "Autoparte")
                        .WithMany("Ofertas")
                        .HasForeignKey("AutoparteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autoparte");
                });

            modelBuilder.Entity("Marimon.Models.OrdenTrabajo", b =>
                {
                    b.HasOne("Marimon.Models.Autoparte", "Autoparte")
                        .WithMany()
                        .HasForeignKey("AutoparteId");

                    b.HasOne("Marimon.Models.Usuario", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId");

                    b.HasOne("Marimon.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autoparte");

                    b.Navigation("Personal");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Marimon.Models.Reclamacion", b =>
                {
                    b.HasOne("Marimon.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Marimon.Models.Resenia", b =>
                {
                    b.HasOne("Marimon.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marimon.Models.Autoparte", "Autoparte")
                        .WithMany()
                        .HasForeignKey("aut_id");

                    b.HasOne("Marimon.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ser_id");

                    b.Navigation("Autoparte");

                    b.Navigation("Servicio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Marimon.Models.Reserva", b =>
                {
                    b.HasOne("Marimon.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marimon.Models.Servicio", "Servicio")
                        .WithMany("Reservas")
                        .HasForeignKey("ser_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Marimon.Models.Salida", b =>
                {
                    b.HasOne("Marimon.Models.Autoparte", "Autoparte")
                        .WithMany()
                        .HasForeignKey("AutoparteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marimon.Models.Comprobante", "Comprobante")
                        .WithMany("Salidas")
                        .HasForeignKey("ComprobanteId");

                    b.Navigation("Autoparte");

                    b.Navigation("Comprobante");
                });

            modelBuilder.Entity("Marimon.Models.Usuario", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithOne()
                        .HasForeignKey("Marimon.Models.Usuario", "usu_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Marimon.Models.Venta", b =>
                {
                    b.HasOne("Marimon.Models.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marimon.Models.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("MetodoPago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marimon.Models.Autoparte", b =>
                {
                    b.Navigation("CodigosDescuento");

                    b.Navigation("Ofertas");
                });

            modelBuilder.Entity("Marimon.Models.Carrito", b =>
                {
                    b.Navigation("CarritoAutopartes");
                });

            modelBuilder.Entity("Marimon.Models.Comprobante", b =>
                {
                    b.Navigation("Boletas");

                    b.Navigation("Facturas");

                    b.Navigation("Salidas");
                });

            modelBuilder.Entity("Marimon.Models.Servicio", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Marimon.Models.Usuario", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Marimon.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
